// All user-facing copy lives here. English only. Components import from
// this file — no inline literal UI text scattered through JSX (aria-labels
// are exempt since they aren't visible copy).

export const strings = {
  app: {
    name: "BM USA Proxy",
    tagline: "USA mobile proxy · 5G unlimited",
  },

  nav: {
    home: "Home",
    catalog: "Catalog",
    access: "Access",
    referral: "Referrals",
    faq: "FAQ",
  },

  common: {
    loading: "Loading…",
    retry: "Retry",
    somethingWrong: "Something went wrong.",
    copy: "Copy",
    copied: "Copied",
    copyAll: "Copy all",
    cancel: "Cancel",
    confirm: "Confirm",
    back: "Back",
    close: "Close",
    save: "Save",
    submit: "Submit",
    any: "Any",
    expired: "Expired",
    expiresIn: "Expires in",
    reveal: "Reveal",
    hide: "Hide",
    optional: "optional",
    required: "required",
  },

  errors: {
    generic: "Something went wrong. Please try again.",
    network: "Couldn't reach the server. Check your connection and retry.",
    soldOut: "This location just sold out. Pick another city or carrier.",
    trialUsed: "Your free trial has already been used.",
    tosRequired: "Please accept the Terms of Service to continue.",
    orderNotFound: "This order could not be found.",
    accessNotFound: "This access could not be found.",
    rotateCooldown: "IP rotation is cooling down. Try again shortly.",
    paymentsUnconfigured:
      "Purchases aren't available yet — an administrator must add a receiving wallet address in the admin console (Wallets) first.",
  },

  openInTelegram: {
    title: "Open via the Telegram bot",
    body: "This mini app only works inside Telegram. Open the bot and tap the app button to continue.",
    cta: "Open @BM_USA_Proxy_bot",
  },

  banned: {
    title: "You have been banned",
    body: "Your access to BM USA Proxy has been suspended. If you believe this is a mistake, contact our support team and we'll take a look.",
    cta: "Contact support",
  },

  home: {
    activeOrdersLabel: "Your orders",
    orderAwaitingPayment: "Awaiting your payment",
    orderInProgress: "Payment received — issuing access",
    heroLabel: "Active access",
    quickActionsLabel: "Quick actions",
    referLabel: "Refer & earn",
    earnedBadge: "Earned",
    noAccessTitle: "No active access yet",
    noAccessBody: "Start with a free trial on a real device, or pick a plan that fits your workflow.",
    getProxyCta: "Get your proxy",
    tileTrialTitle: "Free trial",
    tileTrialSubAvailable: "Real device · one-time",
    tileTrialSubUsed: "Already used",
    tileDailyTitle: "Buy daily",
    tileDailySub: "24h access",
    tileMyAccessTitle: "My access",
    tileMyAccessSubActive: "active package",
    tileMyAccessSubNone: "No active package",
    tileTariffsTitle: "Plans",
    tileTariffsSub: "Daily, Weekly, Monthly · auto-issue",
    // No number here on purpose: this teaser has no access to the live rate, and a stale
    // one is worse than none. The referral screen states the rate, and gets it from the API.
    referTitle: "Refer & earn",
    referSubtitle: "Share your link",
    referAvailableNow: "available now",
    referInvite: "Invite",
    copyAccess: "Copy access",
    rotateIp: "Rotate IP",
    openAccess: "Open access",
    online: "Online",
  },

  catalog: {
    title: "Plans",
    choosePlan: "Choose your plan",
    trialName: "Trial",
    trialMeta: "1 hour · instant real-device test",
    trialAlreadyUsed: "Already used",
    trialCta: "Get free trial",
    dailyName: "Daily",
    dailyMeta: "24 hours · quick tasks",
    weeklyName: "Weekly",
    weeklyMeta: "7 days · social media management",
    monthlyName: "Monthly",
    monthlyMeta: "30 days · business use",
    bestValue: "Best value",
    perDay: "per day",
    perWeek: "per week",
    perMonth: "per month",
    free: "Free",
    autoIssued: "Auto-issued",
    buyPrefix: "Buy",
    paymentsUnavailableCta: "Not available yet",
    resellerTitle: "Reseller / wholesale",
    resellerBody: "Custom pricing · request a quote for bulk access",
    resellerCta: "Request quote",
    resellerFormTitle: "Reseller inquiry",
    resellerFormSubject: "Reseller / wholesale request",
    resellerFormBody: "Tell us about your volume and requirements",
    resellerFormSent: "Your request was sent. We'll reach out via Telegram.",
    coverageLabel: "Coverage",
    payWithSheetTitle: "Set up your proxy",
    buySheetHint: "Pick where the proxy should be, or leave it on Any.",
    payWithSheetHint: "Pick the network first, then the coin — the invoice is created for that one.",
    payNetworkLabel: "Network",
    payNetworkPlaceholder: "Select a network…",
    payCoinLabel: "Coin",
    payCoinPlaceholder: "Select a coin…",
    payCoinDisabled: "Choose a network first",
    payContinue: "Continue to payment",
    buyContinue: "Continue",
    citySelectorLabel: "City",
    carrierSelectorLabel: "Carrier",
    cityFilterLabel: "City",
    carrierFilterLabel: "Carrier",
    slotsFree: "free",
    slotsSoldOut: "Sold out",
    needHelp: "Need help?",
    // Generic labels, not the @username — an operator can point the link at a private
    // invite (e.g. "https://t.me/+AbCdEf"), which has no username to show.
    supportLinkLabel: "Support",
    channelLinkLabel: "Channel",
  },

  checkout: {
    title: "Checkout",
    subtitle: "Crypto invoice",
    selectedPlan: "Selected plan",
    payWith: "Pay with",
    invoice: "Invoice",
    waitingForPayment: "Waiting for payment…",
    confirming: "Confirming payment…",
    provisioning: "Issuing your access…",
    completedTitle: "Access issued",
    completedBody: "Your proxy is ready. Credentials are in your access details.",
    expiredTitle: "Invoice expired",
    expiredBody: "This invoice has expired. Start over to get a new one.",
    manualReviewTitle: "Manual review",
    manualReviewBody: "Your payment needs manual review. Support has been notified — hang tight.",
    cancelledTitle: "Order cancelled",
    cancelledBody: "This order was cancelled.",
    qrHint: "Scan with your phone",
    openInWallet: "Open in wallet",
    iHavePaid: "I've sent the payment",
    iHavePaidWaiting: "Watching the blockchain…",
    seenOnChainTitle: "Payment received",
    seenOnChainBody: "Waiting for the network to confirm it — your proxy is issued automatically.",
    payInWallet: "Pay in wallet",
    simulatePayment: "Simulate payment (dev)",
    cancelAndGoBack: "Cancel & go back",
    retryToCatalog: "Back to catalog",
    openAccess: "Open access",
    autoDeliveredTitle: "Auto-delivered to Telegram",
    autoDeliveredBody:
      "Access credentials arrive as a message within seconds of network confirmation. No manual action required.",
    payAddressLabel: "To",
    amountApprox: "≈",
    left: "left",
  },

  access: {
    title: "My Access",
    activeLabel: "Active access",
    endedLabel: "Access ended",
    endedOnLabel: "Status",
    endedRevoked: "Revoked by support — this proxy is no longer usable.",
    endedExpired: "Expired — the paid period is over.",
    endedFailed: "Provisioning failed — support has been notified.",
    endedBuyNew: "Get a new proxy",
    historyLabel: "History",
    autoRotateLabel: "Auto-rotation",
    autoRotateHint: "Changes the IP on a schedule, without you opening the app.",
    autoRotateEvery: "Every",
    autoRotateMinutesUnit: "minutes",
    autoRotateApply: "Apply",
    autoRotateOnToast: "Auto-rotation is on",
    autoRotateOffToast: "Auto-rotation is off",
    autoRotateRange: "1 to 1440 minutes",
    credentialsLabel: "HTTP proxy",
    socks5CredentialsLabel: "SOCKS5 proxy",
    rotationLinkSectionLabel: "Rotation link",
    rotationLinkLabel: "Link",
    rotationLinkHint: "Opening this link rotates the IP — use it from your own script.",
    combinedLabel: "HTTP · SOCKS5 · rotation link",
    howToConnect: "How to connect",
    rotateIp: "Rotate IP",
    rotateConfirmTitle: "Rotate IP?",
    rotateConfirmBody: "This reboots the real device behind your port. New IP in ~5 seconds.",
    rotateNote: "Rotate IP reboots the real device — new IP in ~5 seconds",
    rotateCoolingPrefix: "Rotate IP",
    extend: "Extend",
    extendSheetTitle: "Extend access",
    swap: "Swap phone",
    swapSheetTitle: "Swap phone",
    swapConfirmTitle: "Swap onto another phone?",
    swapConfirmBody:
      "You move to a different phone, so your host, ports and passwords all change. Your expiry timer keeps running, and the next swap unlocks in 24 hours.",
    swapNextIn: "Next swap in",
    swapDoneToast: "Moved onto a new phone",
    configOvpn: "OpenVPN config",
    configWg: "WireGuard config",
    configSentToast: "Sent to your Telegram chat",
    hostLabel: "Host",
    httpPortLabel: "Port",
    socksPortLabel: "Port",
    loginLabel: "Login",
    passLabel: "Pass",
    ipLabel: "Current IP",
    rotatingHint: "Rotating IP — new address in a moment…",
    newIpPrefix: "New IP:",
    noAccessTitle: "No active access yet",
    noAccessBody: "Start with a free trial on a real device, or pick a plan that fits your workflow.",
    getFreeTrial: "Get free trial",
    viewTariffs: "View plans",
    empty: "Nothing here yet.",
    howToConnectSocks: "SOCKS5",
    howToConnectSocksBody:
      "Recommended. Tunnels all traffic — TCP + UDP. Use socks5h:// so DNS also resolves through the proxy.",
    howToConnectHttp: "HTTP / HTTPS",
    howToConnectHttpBody: "Use when SOCKS5 is unsupported. Compatible with older tools and simple scripts.",
    howToConnectOvpn: "OpenVPN",
    howToConnectOvpnBody: "Request the .ovpn config below — it's delivered to your Telegram chat.",
    howToConnectWg: "WireGuard",
    howToConnectWgBody: "Request the WireGuard config below — it's delivered to your Telegram chat.",
    statusActive: "Active",
    statusExpiring: "Expiring",
    statusProvisioning: "Provisioning",
    statusExpired: "Expired",
    statusCancelled: "Cancelled",
    statusRevoked: "Revoked",
    statusFailed: "Failed",
  },

  referral: {
    title: "Referral cabinet",
    // {pct} is filled from the rate the ledger actually pays (GET /twa/referral). It is
    // operator-editable and moved from 20 to 23, while this copy said 20 — the screen was
    // advertising one deal and the ledger applying another.
    programTitle: "Earn {pct}% on every package",
    programBody:
      "Share your link — receive {pct}% of each purchase your referrals make, instantly credited.",
    yourLink: "Your referral link",
    shareViaTelegram: "Share via Telegram",
    shareText: "Get USA mobile proxy access — SOCKS5/HTTP, real 5G devices.",
    balanceLabel: "Balance",
    holdLabel: "On hold",
    holdNote: "Released when the billing period completes.",
    availableLabel: "Available",
    availableNote: "Ready to withdraw now.",
    requestedLabel: "Requested",
    paidLabel: "Paid out",
    requestPayout: "Request payout",
    payoutFormTitle: "Payout details",
    walletAddress: "Wallet address",
    network: "Network",
    coin: "Coin",
    payoutBelowMin: "Minimum payout is",
    payoutSent: "Payout request sent.",
    opensLabel: "Opened",
    signupsLabel: "Signups",
    earnedLabel: "Earned",
  },

  faq: {
    title: "FAQ & Support",
    commonQuestions: "Common questions",
    contactSupport: "Contact support",
    contactSupportBody: "Responses in minutes",
    // Button label, not the @username — same reasoning as catalog.supportLinkLabel.
    contactSupportCta: "Support",
    newRequest: "New request",
    newRequestFormTitle: "New support request",
    subjectLabel: "Subject",
    bodyLabel: "Message",
    typeLabel: "Type",
    typeSupport: "Support",
    typeReseller: "Reseller",
    typeCustom: "Other",
    requestSent: "Your request was sent.",
    channel: "Channel",
    empty: "No FAQ entries yet.",
  },

  terms: {
    title: "Terms of Service",
    subtitle: "Please review and accept to continue",
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    emailInvalid: "Enter a valid email address.",
    accept: "I accept",
    accepting: "Accepting…",
  },

  sheet: {
    apply: "Apply",
    clear: "Clear",
  },

  toast: {
    copied: "Copied to clipboard",
    configSent: "Sent to your Telegram chat",
    linkCopied: "Link copied",
  },
} as const;
