// All user-facing copy lives here. English only. Components import from
// this file — no inline literal UI text scattered through JSX (aria-labels
// are exempt since they aren't visible copy).

export const strings = {
  app: {
    name: "BM USA Proxy",
    tagline: "USA mobile proxy · 5G unlimited",
  },

  nav: {
    home: "Home",
    catalog: "Catalog",
    access: "Access",
    referral: "Referrals",
    faq: "FAQ",
  },

  common: {
    loading: "Loading…",
    retry: "Retry",
    somethingWrong: "Something went wrong.",
    copy: "Copy",
    copied: "Copied",
    copyAll: "Copy all",
    cancel: "Cancel",
    confirm: "Confirm",
    back: "Back",
    close: "Close",
    save: "Save",
    submit: "Submit",
    any: "Any",
    expired: "Expired",
    expiresIn: "Expires in",
    reveal: "Reveal",
    hide: "Hide",
    optional: "optional",
    required: "required",
  },

  errors: {
    generic: "Something went wrong. Please try again.",
    network: "Couldn't reach the server. Check your connection and retry.",
    soldOut: "This location just sold out. Pick another city or carrier.",
    trialUsed: "Your free trial has already been used.",
    tosRequired: "Please accept the Terms of Service to continue.",
    orderNotFound: "This order could not be found.",
    accessNotFound: "This access could not be found.",
    rotateCooldown: "IP rotation is cooling down. Try again shortly.",
  },

  openInTelegram: {
    title: "Open via the Telegram bot",
    body: "This mini app only works inside Telegram. Open the bot and tap the app button to continue.",
    cta: "Open @BM_USA_Proxy_bot",
  },

  banned: {
    title: "You have been banned",
    body: "Your access to BM USA Proxy has been suspended. If you believe this is a mistake, contact our support team and we'll take a look.",
    cta: "Contact support",
  },

  home: {
    heroLabel: "Active access",
    quickActionsLabel: "Quick actions",
    referLabel: "Refer & earn",
    earnedBadge: "Earned",
    noAccessTitle: "No active access yet",
    noAccessBody: "Start with a free trial on a real device, or pick a plan that fits your workflow.",
    getProxyCta: "Get your proxy",
    tileTrialTitle: "Free trial",
    tileTrialSubAvailable: "Real device · one-time",
    tileTrialSubUsed: "Already used",
    tileDailyTitle: "Buy daily",
    tileDailySub: "24h access",
    tileMyAccessTitle: "My access",
    tileMyAccessSubActive: "active package",
    tileMyAccessSubNone: "No active package",
    tileTariffsTitle: "Tariffs",
    tileTariffsSub: "Daily, Weekly, Monthly · auto-issue",
    referTitle: "Refer & earn 20%",
    referSubtitle: "Share your link",
    referAvailableNow: "available now",
    referInvite: "Invite",
    copyAccess: "Copy access",
    rotateIp: "Rotate IP",
    openAccess: "Open access",
    online: "Online",
  },

  catalog: {
    title: "Tariffs",
    choosePlan: "Choose your plan",
    trialName: "Trial",
    trialMeta: "1 hour · instant real-device test",
    trialAlreadyUsed: "Already used",
    trialCta: "Get free trial",
    dailyName: "Daily",
    dailyMeta: "24 hours · quick tasks",
    weeklyName: "Weekly",
    weeklyMeta: "7 days · social media management",
    monthlyName: "Monthly",
    monthlyMeta: "30 days · business use",
    bestValue: "Best value",
    perDay: "per day",
    perWeek: "per week",
    perMonth: "per month",
    free: "Free",
    autoIssued: "Auto-issued",
    buyPrefix: "Buy",
    resellerTitle: "Reseller / wholesale",
    resellerBody: "Custom pricing · request a quote for bulk access",
    resellerCta: "Request quote",
    resellerFormTitle: "Reseller inquiry",
    resellerFormSubject: "Reseller / wholesale request",
    resellerFormBody: "Tell us about your volume and requirements",
    resellerFormSent: "Your request was sent. We'll reach out via Telegram.",
    coverageLabel: "Coverage",
    citySheetTitle: "Choose city",
    carrierSheetTitle: "Choose carrier",
    citySelectorLabel: "City",
    carrierSelectorLabel: "Carrier",
    slotsFree: "free",
    slotsSoldOut: "Sold out",
    needHelp: "Need help?",
  },

  checkout: {
    title: "Checkout",
    subtitle: "Crypto invoice",
    selectedPlan: "Selected plan",
    payWith: "Pay with",
    invoice: "Invoice",
    waitingForPayment: "Waiting for payment…",
    confirming: "Confirming payment…",
    provisioning: "Issuing your access…",
    completedTitle: "Access issued",
    completedBody: "Your proxy is ready. Credentials are in your access details.",
    expiredTitle: "Invoice expired",
    expiredBody: "This invoice has expired. Start over to get a new one.",
    manualReviewTitle: "Manual review",
    manualReviewBody: "Your payment needs manual review. Support has been notified — hang tight.",
    cancelledTitle: "Order cancelled",
    cancelledBody: "This order was cancelled.",
    payInWallet: "Pay in wallet",
    simulatePayment: "Simulate payment (dev)",
    cancelAndGoBack: "Cancel & go back",
    retryToCatalog: "Back to catalog",
    openAccess: "Open access",
    autoDeliveredTitle: "Auto-delivered to Telegram",
    autoDeliveredBody:
      "Access credentials arrive as a message within seconds of network confirmation. No manual action required.",
    payAddressLabel: "To",
    amountApprox: "≈",
    left: "left",
  },

  access: {
    title: "My Access",
    activeLabel: "Active access",
    historyLabel: "History",
    credentialsLabel: "Proxy credentials",
    combinedLabel: "host:port:login:pass",
    howToConnect: "How to connect",
    rotateIp: "Rotate IP",
    rotateConfirmTitle: "Rotate IP?",
    rotateConfirmBody: "This reboots the real device behind your port. New IP in ~10 seconds.",
    rotateNote: "Rotate IP reboots the real device — new IP in ~10 seconds",
    rotateCoolingPrefix: "Rotate IP",
    extend: "Extend",
    extendSheetTitle: "Extend access",
    swap: "Swap",
    swapSheetTitle: "Swap location",
    swapConfirmTitle: "Confirm swap",
    swapConfirmBody: "Credentials will change after swapping. Your expiry timer keeps running.",
    swapLeft: "swaps left",
    configOvpn: "OpenVPN config",
    configWg: "WireGuard config",
    configSentToast: "Sent to your Telegram chat",
    hostLabel: "Host",
    httpPortLabel: "HTTP",
    socksPortLabel: "SOCKS5",
    loginLabel: "Login",
    passLabel: "Pass",
    ipLabel: "Current IP",
    rotatingHint: "Rotating IP — new address in ~30s…",
    newIpPrefix: "New IP:",
    noAccessTitle: "No active access yet",
    noAccessBody: "Start with a free trial on a real device, or pick a plan that fits your workflow.",
    getFreeTrial: "Get free trial",
    viewTariffs: "View tariffs",
    empty: "Nothing here yet.",
    howToConnectSocks: "SOCKS5",
    howToConnectSocksBody:
      "Recommended. Tunnels all traffic — TCP + UDP. Use socks5h:// so DNS also resolves through the proxy.",
    howToConnectHttp: "HTTP / HTTPS",
    howToConnectHttpBody: "Use when SOCKS5 is unsupported. Compatible with older tools and simple scripts.",
    howToConnectOvpn: "OpenVPN",
    howToConnectOvpnBody: "Request the .ovpn config below — it's delivered to your Telegram chat.",
    howToConnectWg: "WireGuard",
    howToConnectWgBody: "Request the WireGuard config below — it's delivered to your Telegram chat.",
    statusActive: "Active",
    statusExpiring: "Expiring",
    statusProvisioning: "Provisioning",
    statusExpired: "Expired",
    statusCancelled: "Cancelled",
  },

  referral: {
    title: "Referral cabinet",
    programTitle: "Earn 20% on every package",
    programBody: "Share your link — receive 20% of each purchase your referrals make, instantly credited.",
    yourLink: "Your referral link",
    shareViaTelegram: "Share via Telegram",
    shareText: "Get USA mobile proxy access — SOCKS5/HTTP, real 5G devices.",
    balanceLabel: "Balance",
    holdLabel: "On hold",
    holdNote: "Released when the billing period completes.",
    availableLabel: "Available",
    availableNote: "Ready to withdraw now.",
    requestedLabel: "Requested",
    paidLabel: "Paid out",
    requestPayout: "Request payout",
    payoutFormTitle: "Payout details",
    walletAddress: "Wallet address",
    network: "Network",
    payoutBelowMin: "Minimum payout is",
    payoutSent: "Payout request sent.",
    signupsLabel: "Signups",
    clicksLabel: "Clicks",
    earnedLabel: "Earned",
  },

  faq: {
    title: "FAQ & Support",
    commonQuestions: "Common questions",
    contactSupport: "Contact support",
    contactSupportBody: "Responses in minutes",
    newRequest: "New request",
    newRequestFormTitle: "New support request",
    subjectLabel: "Subject",
    bodyLabel: "Message",
    typeLabel: "Type",
    typeSupport: "Support",
    typeReseller: "Reseller",
    typeCustom: "Other",
    requestSent: "Your request was sent.",
    channel: "Channel",
    empty: "No FAQ entries yet.",
  },

  terms: {
    title: "Terms of Service",
    subtitle: "Please review and accept to continue",
    emailLabel: "Email",
    emailPlaceholder: "you@example.com",
    emailInvalid: "Enter a valid email address.",
    accept: "I accept",
    accepting: "Accepting…",
  },

  sheet: {
    apply: "Apply",
    clear: "Clear",
  },

  toast: {
    copied: "Copied to clipboard",
    configSent: "Sent to your Telegram chat",
    linkCopied: "Link copied",
  },
} as const;
