// Single source of truth for user-facing copy. Screens import from here
// instead of inlining strings, so tone/wording stays consistent and is
// trivial to audit or translate later.

export const strings = {
  app: {
    name: "BM USA Proxy",
    tagline: "Admin console",
    topbarTagline: "USA mobile proxy · 5G unlimited",
  },
  auth: {
    loginTitle: "Sign in",
    loginSubtitle: "Operator console access only.",
    emailLabel: "Email",
    passwordLabel: "Password",
    submit: "Sign in",
    submitting: "Signing in…",
    genericError: "Could not sign in. Check your credentials and try again.",
    lockoutFallback: "Too many attempts. Try again later.",
    logout: "Sign out",
  },
  common: {
    loading: "Loading…",
    retry: "Retry",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    close: "Close",
    create: "Create",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    reason: "Reason",
    reasonRequired: "Reason is required",
    search: "Search…",
    refresh: "Refresh",
    copied: "Copied",
    copy: "Copy",
    all: "All",
    ownerOnly: "Owner only",
    noResults: "No results",
    noResultsHint: "Try adjusting your filters.",
    errorTitle: "Couldn't load this",
    errorHint: "Something went wrong on our side. Try again.",
    unsavedWarning: "You have unsaved changes.",
    yes: "Yes",
    no: "No",
    active: "Active",
    inactive: "Inactive",
  },
  nav: {
    groupOperations: "Operations",
    groupContent: "Content",
    groupSystem: "System",
    dashboard: "Dashboard",
    clients: "Clients",
    requests: "Requests",
    pools: "Auto-issue pools",
    packages: "Client packages",
    tariffs: "Tariffs",
    referrals: "Referrals",
    broadcasts: "Broadcasts",
    publications: "Publications",
    faq: "FAQ content",
    notifications: "Notifications",
    settings: "Settings",
  },
  dashboard: {
    title: "Operations dashboard",
    subtitle: "USA 5G mobile proxy network — live state across the pool",
    revenue7d: "Revenue — last 7 days",
    vsPriorWeek: "vs prior week",
    activeAccesses: "Active proxies",
    freePool: "Free pool slots",
    pendingReview: "Pending manual review",
    newRequests: "New requests",
    reviewQueue: "Review queue",
    mapTitle: "Pool network — United States",
    managePools: "Manage pools",
    needsAttention: "Needs attention",
    revenueTrend: "Revenue trend",
  },
  clients: {
    title: "Clients",
    subtitle: "Search, review, and manage client accounts.",
    searchPlaceholder: "Search @username, telegram id, name…",
    filterActive: "Has active access",
    filterBanned: "Banned",
    colClient: "Client",
    colStatus: "Status",
    colAccess: "Access",
    colJoined: "Joined",
    ban: "Ban client",
    unban: "Unban client",
    banConfirm: "This blocks the client from using the bot and any active access. Continue?",
    unbanConfirm: "Restore this client's access to the bot?",
    note: "Operator note",
    noteSaved: "Note saved",
    message: "Send message",
    messagePlaceholder: "Message to the client…",
    messageSent: "Message sent",
    issueAccess: "Issue access",
    dossierTos: "Terms of service",
    dossierAccesses: "Accesses",
    dossierOrders: "Orders",
    dossierReferral: "Referral",
    dossierRequests: "Requests",
    banned: "Banned",
  },
  pools: {
    title: "Auto-issue pools",
    subtitle: "Real-device 5G nodes across US carriers.",
    sync: "Sync now",
    syncing: "Syncing…",
    syncDone: "Pool synced",
    filterCity: "City",
    filterCarrier: "Carrier",
    filterOnline: "Online only",
    filterSellable: "Sellable only",
    sellable: "Sellable",
    slots: "Slots",
    used: "Used",
    free: "Free",
    lastRotated: "Last rotated",
    never: "Never",
    editConnection: "Edit connection",
  },
  packages: {
    title: "Client packages",
    subtitle: "All issued accesses across the fleet.",
    filterStatus: "Status",
    filterCity: "City",
    filterUser: "User",
    filterExpiring: "Expiring soon",
    revoke: "Revoke",
    revokeConfirm: "Revoke this access immediately? The client loses connectivity right away.",
    extend: "Extend",
    extendMinutes: "Minutes to add",
    rotateIp: "Rotate IP",
    rotateIpConfirm: "Rotate the IP for this access now?",
    reissue: "Reissue",
    reissueConnection: "New connection (optional)",
  },
  requests: {
    title: "Requests",
    subtitle: "Support and access requests from clients.",
    colNew: "New",
    colInProgress: "In progress",
    colWaiting: "Waiting",
    colDone: "Done",
    assignee: "Assignee",
    comments: "Comments",
    addComment: "Add comment",
    commentPlaceholder: "Write an internal comment…",
  },
  tariffs: {
    title: "Tariffs",
    subtitle: "Pricing plans offered to clients.",
    create: "New tariff",
    edit: "Edit tariff",
    code: "Code",
    name: "Name",
    priceUsd: "Price (USD)",
    durationDays: "Duration (days)",
    maxUserSwaps: "Max user IP swaps",
    active: "Active",
  },
  orders: {
    title: "Orders & payments",
    subtitle: "Payment processing across all providers.",
    tabAll: "All orders",
    tabManualReview: "Manual review",
    colOrder: "Order",
    colUser: "User",
    colProvider: "Provider",
    colAmount: "Amount",
    colStatus: "Status",
    approve: "Approve",
    fail: "Mark failed",
    refund: "Refund",
    refundAmount: "Refund amount (USD)",
    walletAddress: "Wallet address (optional)",
    txHash: "Transaction hash (optional)",
    markPaid: "Mark paid",
    markPaidReason: "Reason for manual override",
    invoice: "Invoice",
    events: "Event timeline",
  },
  referrals: {
    title: "Referrals",
    subtitle: "Affiliate performance and payouts.",
    totalReferrers: "Referrers",
    totalClicks: "Total clicks",
    totalAttached: "Attached users",
    totalPaid: "Paid out",
    pendingPayouts: "Pending payouts",
    ledger: "Ledger",
    payoutsQueue: "Payouts queue",
    approve: "Approve",
    reject: "Reject",
    markPaid: "Mark paid",
    settings: "Referral settings",
    commissionPct: "Commission %",
    minPayoutUsd: "Minimum payout (USD)",
    cookieDays: "Attribution window (days)",
  },
  broadcasts: {
    title: "Broadcasts",
    subtitle: "One-off messages to a filtered client audience.",
    create: "New broadcast",
    composerTitle: "Compose broadcast",
    titleLabel: "Title",
    bodyLabel: "Message",
    audienceLabel: "Audience filter",
    scheduleFor: "Schedule for",
    sendNow: "Send now",
    schedule: "Schedule",
    progress: "Delivery progress",
  },
  publications: {
    title: "Publications",
    subtitle: "Channel posts and launch announcements.",
    channels: "Channels",
    posts: "Posts",
    newChannel: "New channel",
    newPost: "New post",
    publish: "Publish",
    views: "Views",
    clicks: "Clicks",
  },
  faq: {
    title: "FAQ content",
    subtitle: "Questions shown to clients in the bot.",
    add: "Add question",
    question: "Question",
    answer: "Answer",
    published: "Published",
  },
  notifications: {
    title: "Notifications",
    subtitle: "Operator event log · per-event channel settings",
    markAllRead: "Mark all read",
    eventLog: "Event log",
    settingsTitle: "Notification settings",
    telegram: "Telegram",
    email: "Email",
  },
  settings: {
    title: "Settings",
    subtitle: "App configuration, terms, admins, and audit trail.",
    appSettings: "App settings",
    terms: "Terms of service",
    publish: "Publish",
    addQuestion: "Add question",
    admins: "Admins",
    addAdmin: "Add admin",
    audit: "Audit log",
  },
} as const;
