// Single source of truth for user-facing copy. Screens import from here
// instead of inlining strings, so tone/wording stays consistent and is
// trivial to audit or translate later.

export const strings = {
  app: {
    name: "BM USA Proxy",
    tagline: "Admin console",
  },
  auth: {
    loginTitle: "Sign in",
    loginSubtitle: "Operator console access only.",
    emailLabel: "Email",
    passwordLabel: "Password",
    submit: "Sign in",
    submitting: "Signing in…",
    genericError: "Could not sign in. Check your credentials and try again.",
    lockoutFallback: "Too many attempts. Try again later.",
    logout: "Sign out",
    otpTitle: "Confirm it's you",
    otpLabel: "Sign-in code",
    otpSubmit: "Confirm",
    otpSubmitting: "Checking…",
    otpBack: "Use a different account",
    otpError: "Wrong or expired code. Check the latest message, or start again.",
  },
  common: {
    loading: "Loading…",
    retry: "Retry",
    save: "Save",
    saving: "Saving…",
    cancel: "Cancel",
    close: "Close",
    create: "Create",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    reason: "Reason",
    reasonRequired: "Reason is required",
    refresh: "Refresh",
    copied: "Copied",
    copy: "Copy",
    all: "All",
    ownerOnly: "Owner only",
    noResults: "No results",
    noResultsHint: "Try adjusting your filters.",
    errorTitle: "Couldn't load this",
    errorHint: "Something went wrong on our side. Try again.",
    unsavedWarning: "You have unsaved changes.",
    yes: "Yes",
    no: "No",
    active: "Active",
    inactive: "Inactive",
    // Shared by every table's filter bar — the same control must not be called two
    // different things on two screens.
    clearFilters: "Clear filters",
    clearSearch: "Clear search",
    filterFrom: "From",
    filterTo: "To",
    anyDate: "Any date",
  },
  nav: {
    groupOperations: "Operations",
    groupContent: "Content",
    groupSystem: "System",
    dashboard: "Dashboard",
    clients: "Clients",
    requests: "Requests",
    pools: "Proxies pool",
    packages: "Client packages",
    tariffs: "Plans",
    referrals: "Referrals",
    ledger: "Payments ledger",
    wallets: "Wallets",
    broadcasts: "Broadcasts",
    publications: "Publications",
    faq: "FAQ content",
    notifications: "Notifications",
    settings: "Settings",
  },
  wallets: {
    // "Wallets", not "Receiving wallets": the page grew a payout section, so the narrower
    // name described the top half and quietly denied the bottom one.
    title: "Wallets",
    subtitle:
      "Where customer payments land, and which wallets referral payouts go out from. Editing an address changes where the next payment goes.",
    railsTitle: "Rails",
    railsHint: "Every coin the watcher can handle. Leave an address empty to stop accepting that coin.",
    accepting: "Accepting",
    railOn: "Accepting",
    railOff: "Not accepting",
    receivingAddress: "Receiving address",
    addressPlaceholder: "Paste the wallet address, or leave empty to stop accepting this coin",
    contract: "Contract",
    confirmations: "Confirms",
    chainNetwork: "Chain network",
    watching: "Watcher live",
    notWatching: "Watcher off",
    notWatchingHint:
      "PAYMENT_PROVIDER is not set to \"onchain\", so nothing is scanning these addresses. Money sent to them will not be credited to an order until it is.",
    fromEnvHint:
      "These addresses currently come from ONCHAIN_METHODS in the deploy environment. Saving here takes over from it — after that, this screen is what decides.",
    configError: "The stored rail list could not be read",
    saved: "Rails saved — new invoices quote these addresses",
    payoutTitle: "Payout wallets",
    payoutHint:
      "The wallets referral payouts are sent FROM. Nothing is received here — they are watched so a payout you send by hand gets its transaction hash attached on its own. Payouts are USDT only, on these three networks.",
    payoutPlaceholder: "Address you send referral payouts from",
    payoutOn: "Watched",
    payoutOff: "Not set",
    confirmTitle: "Save receiving wallets",
    confirmNoAddressChange: "No address changes — only confirmation counts. Save?",
    confirmAddressChange:
      "From now on every new invoice quotes these addresses. Money sent to a replaced address will not be credited automatically. Check each one against the wallet before saving.",
  },
  dashboard: {
    title: "Operations dashboard",
    subtitle: "USA 5G mobile proxy network — live state across the pool",
    revenue7d: "Revenue — last 7 days",
    vsPriorWeek: "vs prior week",
    // "Busy", not "Active": it counts proxies a client is holding right now, which is the
    // same state the pools screen and the device chips call Busy. One word per state.
    activeAccesses: "Busy proxies",
    freePool: "Free pool slots",
    pendingReview: "Pending manual review",
    newRequests: "New requests",
    reviewQueue: "Review queue",
    needsAttention: "Needs attention",
    revenueTrend: "Revenue trend",
  },
  clients: {
    title: "Clients",
    subtitle: "Search, review, and manage client accounts.",
    searchPlaceholder: "Search @username, telegram id, name…",
    filterActive: "Has active access",
    filterBanned: "Banned",
    colClient: "Client",
    colStatus: "Status",
    colAccess: "Access",
    colJoined: "Joined",
    ban: "Ban client",
    unban: "Unban client",
    banConfirm: "This blocks the client from using the bot and any active access. Continue?",
    unbanConfirm: "Restore this client's access to the bot?",
    note: "Operator note",
    noteSaved: "Note saved",
    message: "Send message",
    messagePlaceholder: "Message to the client…",
    messageSent: "Message sent",
    issueAccess: "Issue access",
    /** Tooltip on the compact checkmark next to a client's handle in the table row. */
    termsAccepted: "Terms of Use accepted",
    dossierTos: "Terms of service",
    dossierConversation: "Conversation",
    dossierAccesses: "Accesses",
    dossierOrders: "Orders",
    dossierReferral: "Referral",
    dossierRequests: "Requests",
    banned: "Banned",
    conversationEmpty: "No messages yet",
    conversationClient: "Client",
    conversationOperator: "Operator",
  },
  pools: {
    title: "Proxies pool",
    subtitle: "Real-device 5G nodes across US carriers.",
    sync: "Sync now",
    syncing: "Syncing…",
    syncDone: "Pool synced",
    filterCity: "City",
    filterCarrier: "Carrier",
    filterOnline: "Online only",
    filterSellable: "Sellable only",
    searchPlaceholder: "Search device id, city, carrier, tier, note…",
    sellable: "Sellable",
    slots: "Slots",
    // "Busy" everywhere a slot is occupied, matching the chip on the device card. One word
    // for one state across the screen, and it reads right about a phone as well as a slot.
    used: "Busy",
    free: "Free",
    lastRotated: "Last rotated",
    never: "Never",
    editConnection: "Edit connection",
  },
  packages: {
    title: "Client packages",
    subtitle: "All issued accesses across the fleet.",
    filterStatus: "Status",
    filterCity: "City",
    filterUser: "User",
    filterExpiring: "Expiring soon",
    colOrder: "Order",
    searchPlaceholder: "Search user, status, city, carrier, tariff, order…",
    revoke: "Revoke",
    revokeConfirm: "Revoke this access immediately? The client loses connectivity right away.",
    extend: "Extend",
    extendMinutes: "Minutes to add",
    rotateIp: "Rotate IP",
    rotateIpConfirm: "Rotate the IP for this access now?",
    reissue: "Reissue",
    reissueConnection: "New connection (optional)",
    cannotRevoke: "Already revoked — nothing left to revoke",
    cannotExtend: "This access is no longer usable — reissue it instead of extending it",
    cannotRotate: "Only a live access has a connection to rotate",
  },
  requests: {
    title: "Requests",
    subtitle: "Support and access requests from clients.",
    colNew: "New",
    colInProgress: "In progress",
    colWaiting: "Waiting",
    colDone: "Done",
    assignee: "Assignee",
    comments: "Comments",
    addComment: "Add comment",
    commentPlaceholder: "Write an internal comment…",
  },
  tariffs: {
    title: "Plans",
    subtitle: "Pricing plans offered to clients.",
    create: "New plan",
    edit: "Edit plan",
    code: "Code",
    name: "Name",
    priceUsd: "Price (USD)",
    durationMinutes: "Duration (minutes)",
    duration: "Duration",
    durationUnit: "Unit",
    maxUserSwaps: "Max user IP swaps",
    active: "Active",
  },
  orders: {
    title: "Orders & payments",
    subtitle: "Payment processing across all providers.",
    tabAll: "All orders",
    tabManualReview: "Manual review",
    colOrder: "Order",
    colUser: "User",
    colProvider: "Provider",
    colAmount: "Amount",
    colStatus: "Status",
    approve: "Approve",
    fail: "Mark failed",
    refund: "Refund",
    refundAmount: "Refund amount (USD)",
    walletAddress: "Wallet address (optional)",
    txHash: "Transaction hash (optional)",
    markPaid: "Mark paid",
    markPaidReason: "Reason for manual override",
    invoice: "Invoice",
    events: "Event timeline",
  },
  ledger: {
    title: "Payments ledger",
    subtitle: "Every on-chain deposit the watcher observed — append-only audit trail.",
    events24h: "Events (24h)",
    unmatched: "Unmatched",
    colAction: "",
    viewCurrent: "Current state",
    viewHistory: "Full history",
    resolve: "Resolve",
    reopen: "Reopen",
    resolveTitle: "Resolve deposit",
    attachLabel: "Credit it to an order",
    attachPlaceholder: "…or type an order number, e.g. 412",
    candidateExact: "exact match",
    candidatesEmpty: "No open orders on this rail — check the write-off option below.",
    attachAction: "Attach & issue access",
    writeOffLabel: "Or close it without crediting anyone",
    writeOffPlaceholder: "Reason (refunded elsewhere, dust, …)",
    writeOffAction: "Write off",
    filterStatus: "Status",
    filterChain: "Chain",
    filterAsset: "Coin",
    filterView: "View",
    filterFrom: "From",
    filterTo: "To",
    filterAnyDate: "Any date",
    searchPlaceholder: "Search coin, chain, tx hash, from / to address…",
    clearFilters: "Clear filters",
    colTime: "Time",
    colChain: "Chain / asset",
    colStatus: "Status",
    colAmount: "Amount",
    colTx: "Tx",
    colFrom: "From",
    colTo: "To",
    colUser: "User",
    colOrder: "Order",
    empty: "No on-chain deposits observed yet",
    emptyFiltered: "No deposits match these filters",
    emptyFilteredHint: "Widen the date range, or clear the filters to see everything.",
  },
  referrals: {
    title: "Referrals",
    subtitle: "Affiliate performance and payouts.",
    totalReferrers: "Referrers",
    totalClicks: "Link opens",
    totalAttached: "Attached users",
    totalPaid: "Paid out",
    pendingPayouts: "Pending payouts",
    payoutSearchPlaceholder: "Search referrer, referral code, network, wallet, tx hash…",
    ledgerSearchPlaceholder: "Search referrer, status, referral code…",
    ledger: "Ledger",
    payoutsQueue: "Payouts queue",
    approve: "Approve",
    reject: "Reject",
    markPaid: "Mark paid",
    settings: "Referral settings",
    commissionPct: "Commission %",
    minPayoutUsd: "Minimum payout (USD)",
    // Short enough to sit on one line beside the other two fields at this column width.
    holdDays: "Payout hold (days)",
    send: "Send",
    sendPayout: "Send payout",
    amountToSend: "Amount to send",
    network: "Network",
    toAddress: "To address",
    openInWallet: "Open in wallet →",
    qrAlt: "QR code with the payout address",
    qrHint: "Scan with the wallet you send payouts from",
    alreadyConfirmed: "Already confirmed on-chain",
  },
  broadcasts: {
    title: "Broadcasts",
    subtitle: "One-off messages to a filtered client audience.",
    create: "New broadcast",
    composerTitle: "Compose broadcast",
    titleLabel: "Title",
    bodyLabel: "Message",
    audienceLabel: "Audience filter",
    scheduleFor: "Schedule for",
    sendNow: "Send now",
    schedule: "Schedule",
    progress: "Delivery progress",
  },
  publications: {
    title: "Publications",
    subtitle: "Channel posts and launch announcements.",
    channels: "Channels",
    posts: "Posts",
    newChannel: "New channel",
    newPost: "New post",
    publish: "Publish",
    views: "Views",
    clicks: "Clicks",
  },
  faq: {
    title: "FAQ content",
    subtitle: "Questions shown to clients in the bot.",
    add: "Add question",
    question: "Question",
    answer: "Answer",
    published: "Published",
  },
  notifications: {
    title: "Notifications",
    subtitle: "Operator event log · message templates",
    markAllRead: "Mark all read",
    eventLog: "Event log",
    settingsTitle: "Message templates",
    settingsSubtitle: "Edit the text clients receive. Leave blank to use the default.",
    settingsPlaceholder: "Default text",
    settingsSaved: "Templates saved",
    telegram: "Telegram",
    email: "Email",
  },
  settings: {
    title: "Settings",
    subtitle: "App configuration, terms, admins, and audit trail.",
    appSettings: "App settings",
    welcomeImage: "Welcome image",
    welcomeImageHint:
      "Sent as a photo with the bot's /start greeting, the same buttons in the caption. JPEG, PNG, or WebP, up to 5 MB.",
    welcomeImageReplace: "Replace image",
    welcomeImageUploaded: "Welcome image updated",
    welcomeImageBadType: "Use a JPEG, PNG, or WebP image.",
    welcomeImageTooLarge: "Image is larger than 5 MB.",
    terms: "Terms of service",
    termsSubtitle: "What clients read and accept before the mini-app lets them buy.",
    termsText: "Agreement text (Markdown)",
    termsTextHint:
      "Shown on the acceptance screen in the mini-app. Markdown: ## heading, **bold**, - list.",
    termsQuestions: "Questions asked on acceptance",
    termsQuestionsHint:
      "Answers are stored with the acceptance and shown in the client's dossier. The seeded email question is what gives you a contact address outside Telegram.",
    termsPublishHint:
      "Save updates the text for everyone immediately. Publish also bumps the version, which puts every existing client back through the acceptance screen — use it for changes of substance, not typos.",
    termsPublishConfirm:
      "Publish a new version? Every client will have to accept the terms again before they can use the app.",
    publish: "Publish new version",
    addQuestion: "Add question",
    admins: "Admins",
    password: "Password",
    newPassword: "New password",
    repeatPassword: "Repeat new password",
    changePassword: "Change password",
    passwordsDiffer: "The two do not match.",
    passwordChanged: "Password changed — that account is now signed out everywhere.",
    generatePassword: "Generate a strong one",
    // Says the thing the interface would otherwise have to be asked about: there is no
    // screen anywhere that can show an existing password, and this is why.
    passwordNotStored:
      "Only a hash of the password is stored, so it can never be shown again — reveal it here and copy it now if you need to pass it on.",
    newPasswordHint:
      "Changing it signs this account out everywhere immediately — including you, if it is your own. Use it when someone leaves: their open session ends at once rather than lasting until the login cookie expires.",
    addAdmin: "Add admin",
    deleteAdmin: "Delete account",
    deleteAdminConfirm: "Delete this account?",
    deleteAdminBody:
      "The account and its sign-in are gone for good. Anything it did — refunds, payouts, audit entries — stays, but stops carrying a name. The deletion itself is recorded with the email, so there is still an answer to who this was.",
    adminDeleted: "Account deleted",
    audit: "Audit log",
    auditSearchPlaceholder: "Search admin, entity, action…",
  },
} as const;
