"""core schema

Revision ID: ffed8d9215e2
Revises: 0001_extensions
Create Date: 2026-07-02 23:23:35.053530

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002_core_schema'
down_revision: str | None = '0001_extensions'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default='operator', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('failed_logins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner','operator')", name=op.f('ck_admin_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('email', name=op.f('uq_admin_users_email'))
    )
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    sa.UniqueConstraint('tg_chat_id', name=op.f('uq_channels_tg_chat_id'))
    )
    op.create_table('locations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('state_code', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('city', 'state_code', name='city_state')
    )
    op.create_table('payment_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_event_id', sa.Text(), nullable=True),
    sa.Column('provider_invoice_id', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_events'))
    )
    op.create_index('uq_payment_events_dedupe', 'payment_events', ['provider', 'provider_event_id'], unique=True, postgresql_where=sa.text('provider_event_id IS NOT NULL'))
    op.create_table('tariffs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('kind', sa.Text(), server_default='auto', nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('max_per_user', sa.Integer(), nullable=True),
    sa.Column('max_user_swaps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('auto_issue', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('auto','manual')", name=op.f('ck_tariffs_kind_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tariffs')),
    sa.UniqueConstraint('code', name=op.f('uq_tariffs_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('lang', sa.Text(), server_default='en', nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('referral_code', sa.Text(), nullable=False),
    sa.Column('referrer_user_id', sa.BigInteger(), nullable=True),
    sa.Column('referral_bound_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_post_id', sa.BigInteger(), nullable=True),
    sa.Column('is_bot_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('operator_note', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','banned')", name=op.f('ck_users_status_valid')),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], name=op.f('fk_users_referrer_user_id_users')),
    sa.ForeignKeyConstraint(['source_post_id'], ['posts.id'], name='fk_users_source_post_id_posts', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('referral_code', name=op.f('uq_users_referral_code')),
    sa.UniqueConstraint('tg_user_id', name=op.f('uq_users_tg_user_id'))
    )
    op.create_index('ix_users_referrer', 'users', ['referrer_user_id'], unique=False, postgresql_where='referrer_user_id IS NOT NULL')
    op.create_index('ix_users_username', 'users', ['tg_username'], unique=False)
    op.create_table('app_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], name=op.f('fk_app_settings_updated_by_admin_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name=op.f('fk_audit_log_admin_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_entity', 'audit_log', ['entity', 'entity_id'], unique=False)
    op.create_table('broadcasts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('audience_filter', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','scheduled','sending','done','failed','cancelled')", name=op.f('ck_broadcasts_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], name=op.f('fk_broadcasts_created_by_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcasts'))
    )
    op.create_table('connections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('iproxy_connection_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), server_default='', nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('carrier', sa.Text(), nullable=True),
    sa.Column('tier', sa.Text(), server_default='standard', nullable=False),
    sa.Column('is_sellable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('online_status', sa.Text(), server_default='unknown', nullable=False),
    sa.Column('last_online_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_note', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("carrier IN ('T-Mobile','Verizon','AT&T') OR carrier IS NULL", name=op.f('ck_connections_carrier_valid')),
    sa.CheckConstraint("online_status IN ('online','offline','unknown')", name=op.f('ck_connections_online_status_valid')),
    sa.CheckConstraint("tier IN ('stable','standard','reserved')", name=op.f('ck_connections_tier_valid')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_connections_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connections')),
    sa.UniqueConstraint('iproxy_connection_id', name=op.f('uq_connections_iproxy_connection_id'))
    )
    op.create_index('ix_connections_pool', 'connections', ['is_sellable', 'online_status', 'location_id'], unique=False)
    op.create_table('faq_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Text(), server_default='general', nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['admin_users.id'], name=op.f('fk_faq_items_updated_by_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faq_items'))
    )
    op.create_table('notifications_outbox',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('template_code', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending','sent','failed','blocked','skipped')", name=op.f('ck_notifications_outbox_status_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_outbox_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications_outbox'))
    )
    op.create_index('ix_outbox_due', 'notifications_outbox', ['status', 'scheduled_at'], unique=False, postgresql_where="status = 'pending'")
    op.create_index('uq_outbox_dedupe', 'notifications_outbox', ['dedupe_key'], unique=True, postgresql_where='dedupe_key IS NOT NULL')
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tariff_id', sa.BigInteger(), nullable=False),
    sa.Column('tariff_code', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('carrier', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='awaiting_payment', nullable=False),
    sa.Column('is_extension', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('extends_access_id', sa.BigInteger(), nullable=True),
    sa.Column('origin', sa.Text(), server_default='twa', nullable=False),
    sa.Column('referrer_user_id', sa.BigInteger(), nullable=True),
    sa.Column('source_post_id', sa.BigInteger(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("carrier IN ('T-Mobile','Verizon','AT&T') OR carrier IS NULL", name=op.f('ck_orders_carrier_valid')),
    sa.CheckConstraint("origin IN ('twa','admin')", name=op.f('ck_orders_origin_valid')),
    sa.CheckConstraint("status IN ('awaiting_payment','paid','provisioning','completed','cancelled','expired','refunded','manual_review')", name=op.f('ck_orders_status_valid')),
    sa.ForeignKeyConstraint(['extends_access_id'], ['accesses.id'], name='fk_orders_extends_access_id_accesses', use_alter=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_orders_location_id_locations')),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], name=op.f('fk_orders_referrer_user_id_users')),
    sa.ForeignKeyConstraint(['source_post_id'], ['posts.id'], name='fk_orders_source_post_id_posts', use_alter=True),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], name=op.f('fk_orders_tariff_id_tariffs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('public_id', name=op.f('uq_orders_public_id'))
    )
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False, postgresql_where=sa.text("status IN ('awaiting_payment','provisioning','manual_review')"))
    op.create_index('ix_orders_user', 'orders', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('referrer_user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('wallet_address', sa.Text(), nullable=False),
    sa.Column('network', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='requested', nullable=False),
    sa.Column('operator_id', sa.BigInteger(), nullable=True),
    sa.Column('tx_hash', sa.Text(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('requested','approved','paid','rejected')", name=op.f('ck_payouts_status_valid')),
    sa.ForeignKeyConstraint(['operator_id'], ['admin_users.id'], name=op.f('fk_payouts_operator_id_admin_users')),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], name=op.f('fk_payouts_referrer_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payouts'))
    )
    op.create_index('ix_payouts_queue', 'payouts', ['status', 'requested_at'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('deep_link_code', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','scheduled','posted','failed','deleted')", name=op.f('ck_posts_status_valid')),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_posts_channel_id_channels')),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], name=op.f('fk_posts_created_by_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts')),
    sa.UniqueConstraint('deep_link_code', name=op.f('uq_posts_deep_link_code'))
    )
    op.create_index('ix_posts_due', 'posts', ['status', 'scheduled_at'], unique=False, postgresql_where="status = 'scheduled'")
    op.create_table('requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='new', nullable=False),
    sa.Column('assignee_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('new','in_progress','done','rejected')", name=op.f('ck_requests_status_valid')),
    sa.CheckConstraint("type IN ('reseller','support','refund','custom')", name=op.f('ck_requests_type_valid')),
    sa.ForeignKeyConstraint(['assignee_id'], ['admin_users.id'], name=op.f('fk_requests_assignee_id_admin_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_requests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests'))
    )
    op.create_index('ix_requests_board', 'requests', ['status', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('tos_acceptances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('bot','twa')", name=op.f('ck_tos_acceptances_source_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tos_acceptances_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tos_acceptances')),
    sa.UniqueConstraint('user_id', 'version', name='user_version')
    )
    op.create_table('accesses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('connection_id', sa.BigInteger(), nullable=False),
    sa.Column('tariff_code', sa.Text(), nullable=False),
    sa.Column('iproxy_access_id', sa.Text(), nullable=True),
    sa.Column('credentials_enc', sa.LargeBinary(), nullable=True),
    sa.Column('status', sa.Text(), server_default='provisioning', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('warned_24h_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warned_1h_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_rotation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotations_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('swap_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('provisioning','active','expiring','expired','revoked','failed')", name=op.f('ck_accesses_status_valid')),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_accesses_connection_id_connections')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_accesses_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_accesses_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accesses')),
    sa.UniqueConstraint('public_id', name=op.f('uq_accesses_public_id'))
    )
    op.create_index('ix_accesses_sweep', 'accesses', ['status', 'expires_at'], unique=False, postgresql_where=sa.text("status IN ('active','expiring')"))
    op.create_index('ix_accesses_user', 'accesses', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('uq_connection_active_access', 'accesses', ['connection_id'], unique=True, postgresql_where=sa.text("status IN ('provisioning','active','expiring')"))
    op.create_table('broadcast_deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('broadcast_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','sent','failed','blocked')", name=op.f('ck_broadcast_deliveries_status_valid')),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], name=op.f('fk_broadcast_deliveries_broadcast_id_broadcasts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_broadcast_deliveries_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broadcast_deliveries')),
    sa.UniqueConstraint('broadcast_id', 'user_id', name='broadcast_user')
    )
    op.create_index('ix_bdeliv_pending', 'broadcast_deliveries', ['broadcast_id', 'status'], unique=False, postgresql_where="status = 'pending'")
    op.create_table('invoices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_invoice_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='created', nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('crypto_currency', sa.Text(), nullable=True),
    sa.Column('crypto_network', sa.Text(), nullable=True),
    sa.Column('crypto_amount', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('pay_address', sa.Text(), nullable=True),
    sa.Column('payment_url', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('created','pending','confirming','paid','underpaid','overpaid','expired','failed','manual_review')", name=op.f('ck_invoices_status_valid')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_invoices_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('provider', 'provider_invoice_id', name='provider_invoice')
    )
    op.create_index('ix_invoices_order', 'invoices', ['order_id'], unique=False)
    op.create_index('ix_invoices_pending', 'invoices', ['status', 'expires_at'], unique=False, postgresql_where=sa.text("status IN ('created','pending','confirming')"))
    op.create_table('referral_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('referrer_user_id', sa.BigInteger(), nullable=False),
    sa.Column('referee_user_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), server_default='accrual', nullable=False),
    sa.Column('base_amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Text(), server_default='hold', nullable=False),
    sa.Column('hold_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payout_id', sa.BigInteger(), nullable=True),
    sa.Column('reversal_of_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('accrual','reversal')", name=op.f('ck_referral_ledger_kind_valid')),
    sa.CheckConstraint("status IN ('hold','available','requested','paid','reversed')", name=op.f('ck_referral_ledger_status_valid')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_referral_ledger_order_id_orders')),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], name='fk_referral_ledger_payout_id_payouts', use_alter=True),
    sa.ForeignKeyConstraint(['referee_user_id'], ['users.id'], name=op.f('fk_referral_ledger_referee_user_id_users')),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], name=op.f('fk_referral_ledger_referrer_user_id_users')),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['referral_ledger.id'], name=op.f('fk_referral_ledger_reversal_of_id_referral_ledger')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_ledger'))
    )
    op.create_index('ix_ledger_referrer', 'referral_ledger', ['referrer_user_id', 'status'], unique=False)
    op.create_index('ix_ledger_release', 'referral_ledger', ['status', 'hold_until'], unique=False, postgresql_where="status = 'hold'")
    op.create_index('uq_ledger_accrual_per_order', 'referral_ledger', ['order_id'], unique=True, postgresql_where="kind = 'accrual'")
    op.create_table('refunds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('wallet_address', sa.Text(), nullable=True),
    sa.Column('tx_hash', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['admin_users.id'], name=op.f('fk_refunds_operator_id_admin_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_refunds_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_table('request_comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('author_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_admin_id'], ['admin_users.id'], name=op.f('fk_request_comments_author_admin_id_admin_users')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_request_comments_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_comments'))
    )
    op.create_table('access_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('access_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('issued','rotate_ip','extended','expiry_warning','expired','revoked','reissued','config_delivered','provision_failed')", name=op.f('ck_access_events_type_valid')),
    sa.ForeignKeyConstraint(['access_id'], ['accesses.id'], name=op.f('fk_access_events_access_id_accesses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_events'))
    )
    op.create_index('ix_access_events_access', 'access_events', ['access_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###

    # Cyclic / forward-referencing FKs, added after all tables exist (use_alter).
    op.create_foreign_key('fk_users_source_post_id_posts', 'users', 'posts', ['source_post_id'], ['id'])
    op.create_foreign_key('fk_orders_source_post_id_posts', 'orders', 'posts', ['source_post_id'], ['id'])
    op.create_foreign_key('fk_orders_extends_access_id_accesses', 'orders', 'accesses', ['extends_access_id'], ['id'])
    op.create_foreign_key('fk_referral_ledger_payout_id_payouts', 'referral_ledger', 'payouts', ['payout_id'], ['id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_source_post_id_posts', 'users', type_='foreignkey')
    op.drop_constraint('fk_orders_source_post_id_posts', 'orders', type_='foreignkey')
    op.drop_constraint('fk_orders_extends_access_id_accesses', 'orders', type_='foreignkey')
    op.drop_constraint('fk_referral_ledger_payout_id_payouts', 'referral_ledger', type_='foreignkey')
    op.drop_index('ix_access_events_access', table_name='access_events')
    op.drop_table('access_events')
    op.drop_table('request_comments')
    op.drop_table('refunds')
    op.drop_index('uq_ledger_accrual_per_order', table_name='referral_ledger', postgresql_where="kind = 'accrual'")
    op.drop_index('ix_ledger_release', table_name='referral_ledger', postgresql_where="status = 'hold'")
    op.drop_index('ix_ledger_referrer', table_name='referral_ledger')
    op.drop_table('referral_ledger')
    op.drop_index('ix_invoices_pending', table_name='invoices', postgresql_where=sa.text("status IN ('created','pending','confirming')"))
    op.drop_index('ix_invoices_order', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_bdeliv_pending', table_name='broadcast_deliveries', postgresql_where="status = 'pending'")
    op.drop_table('broadcast_deliveries')
    op.drop_index('uq_connection_active_access', table_name='accesses', postgresql_where=sa.text("status IN ('provisioning','active','expiring')"))
    op.drop_index('ix_accesses_user', table_name='accesses')
    op.drop_index('ix_accesses_sweep', table_name='accesses', postgresql_where=sa.text("status IN ('active','expiring')"))
    op.drop_table('accesses')
    op.drop_table('tos_acceptances')
    op.drop_index('ix_requests_board', table_name='requests')
    op.drop_table('requests')
    op.drop_index('ix_posts_due', table_name='posts', postgresql_where="status = 'scheduled'")
    op.drop_table('posts')
    op.drop_index('ix_payouts_queue', table_name='payouts')
    op.drop_table('payouts')
    op.drop_index('ix_orders_user', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders', postgresql_where=sa.text("status IN ('awaiting_payment','provisioning','manual_review')"))
    op.drop_table('orders')
    op.drop_index('uq_outbox_dedupe', table_name='notifications_outbox', postgresql_where='dedupe_key IS NOT NULL')
    op.drop_index('ix_outbox_due', table_name='notifications_outbox', postgresql_where="status = 'pending'")
    op.drop_table('notifications_outbox')
    op.drop_table('faq_items')
    op.drop_index('ix_connections_pool', table_name='connections')
    op.drop_table('connections')
    op.drop_table('broadcasts')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_settings')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_referrer', table_name='users', postgresql_where='referrer_user_id IS NOT NULL')
    op.drop_table('users')
    op.drop_table('tariffs')
    op.drop_index('uq_payment_events_dedupe', table_name='payment_events', postgresql_where=sa.text('provider_event_id IS NOT NULL'))
    op.drop_table('payment_events')
    op.drop_table('locations')
    op.drop_table('channels')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
